displayName=Infected Partymode
author=SypherRed
description=A Party Plugin to play "Infected" together, similar to Manhunt.
tags=party,infected,
plugins=com.sypherred.infectedpartymode.InfectedPartymodePlugin